### ISSUE TITLE
Pas mal, mais...

### ISSUE THREAD

**Issue by tspoke** [Foohx/blacklion#1]
Effectivement ça ne respecte pas les CGU ;)

Spoke.

**Comment by Foohx** [comment]
Coucou Spoke,

> Effectivement ça ne respecte pas les CGU ;)

C'est d'une logique implacable. 👍 
J'ai surtout fait ça (à mes heures perdues) dans le but de redonner un peu vie au jeu. Le fait de voir pas mal de monde de connecté (grâce aux bots), en a remotivé certains ou du moins je l'espère.. 

D'ailleurs, j'en ai discuté l'autre jour avec @snwfdhmp sur Skype, et il s'avère qu'à notre grand désespoir, 3GM soit en train de mourir à petit feu. Pour les nouveaux joueurs, il devient difficile voir impossible de rattraper ou bien même d'avoir la moindre chance de victoire face aux plus gros comptes déjà en place depuis longtemps. De plus le template ainsi que quelques mécaniques du jeu commencent à vieillir. 

Ne serais-ce pas une bonne chose, de rendre le jeu open source en partie ou dans sa totalité, de revoir quelques morceaux du gameplay, ou pourquoi pas d'évoluer vers quelque chose de nouveau ?

Je sais que tu avais ça en projet (une évolution vers un nouveau truc) pendant un temps et je serais ravie d'avoir ton avis sur toutes ces choses (Ici ou ailleurs).

Foohx.

**Comment by tspoke** [comment]
Je comprend bien que certains sont tentés de bypasser le système, j'aurais probablement fais la même :)

Oui 3gm est un peu mort, principalement par ma faute car j'ai un peu quitté le navire il y a quelque temps maintenant. J'avais investi beaucoup de temps dans le projet et il était l'heure de passer à autre chose. Cela dit, même si le code est immonde, ça reste une très bonne expérience et de très bons souvenirs (code et ingame) :)

Oui, les nouveaux n'ont aucune chance sur les serveurs actuels, je pensais éventuellement en lancer un nouveau mais est-ce bien utile ?

Pour l'évolution de 3gm, actuellement ce n'est pas envisageable de continuer d'ajouter des features ou de le patcher, ça devient risqué. C'est une vieille machine rouillée qu'il ne faut pas trop brusquer haha.
Plus sérieusement je ne souhaites pas mettre open-source le code, principalement parce qu'il n'apporte rien techniquement et que ça serait peine perdue pour y ajouter des features pour la communauté. Il n'y a rien de critique ou de secret derrière le code de 3gm, ça se résume à des fonctions de gestion.
J'avais voulu pendant un temps faire une nouvelle version un peu plus au gout du jour. Je voulais faire quelque chose de plus dynamique/graphique avec une carte telle que Lord of Ultima et j'avais écrit pas mal d'idées autours du jeu (qui étaient issue de 3gm + de nouveaux concepts).
Deux problèmes majeurs : manque de graphismes (couteux), manque de temps.

Maintenant, je ne dis pas non pour la création d'un nouveau jeu en ligne. Pas forcément open-source (même si c'est envisageable) mais avec une équipe mature de développeurs/graphistes.
Je suis prêt à en discuter, et à y participer activement si d'autres personnes sont motivées par un tel projet. Mais il faut se rendre compte que ça prend beaucoup de temps (plusieurs mois facilement) pour avoir une beta et que, si on y va, faut y aller sérieusement.

Spoke.
